source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

workspace 'GKBaseKitExample'

target :'GKBaseKitExample' do
    project 'GKBaseKitExample.xcodeproj'
    platform :ios, '9.0'

    pod 'GKBaseKit', :path => '../'

    target :'GKBaseKitTests' do
        pod 'Nimble', '~> 8.x'
    end
end
