name: Pod lint

on: push

jobs:
  pod-lint:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.1.app

    - name: Pod lint
      run: pod lib lint
      shell: zsh