name: Pod lint

on: push

jobs:
  pod-lint:
    runs-on: macos-latest
    strategy:
      matrix:
        xcodeVersions: ['9.0', '13.0', '13.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcodeVersions }}

    - name: Pod lint
      run: pod lib lint
      shell: zsh